### ISSUE TITLE
Steps after step 3 are missing db creation

### ISSUE THREAD

**Issue by botlove** [nearform/micro-services-tutorial-iot#13]
Unlike the developing-microservices walk-through, this one requires bits and pieces from various steps in order to run the previous steps solutions. The one that's obvious from the fuge shell output is the missing temperature database.

Try removing your existing docker images and running the solutions.

**Comment by mcdonnelldean** [comment]
Merged with #23 Scripts are being converted to bat, we'll add them with this. CC @mihaidma
