### ISSUE TITLE
NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp

### ISSUE THREAD

**Issue by botlove** [nearform/micro-services-tutorial-iot#15]
```js
osx:v10.11.4 git:v2.6.4 v8:v4.5.103.35 node:v4.4.1 npm:v3.8.5 nvm:v0.31.0
micro-services-tutorial-iot/ on master
λ npm install

> zmq@2.14.0 install /Users/rocky.assad/code/micro-services-tutorial-iot/node_modules/zmq
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
gyp: Call to 'pkg-config libzmq --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/rocky.assad/.nvm/versions/node/v4.4.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/Users/rocky.assad/.nvm/versions/node/v4.4.1/bin/node" "/Users/rocky.assad/.nvm/versions/node/v4.4.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rocky.assad/code/micro-services-tutorial-iot/node_modules/zmq
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:zmq@2.14.0 zmq@2.14.0 install: `node-gyp rebuild`
npm WARN install:zmq@2.14.0 Exit status 1
npm WARN microservices-tutorial-iot@1.0.0 No repository field.
```

**Comment by Ameobea** [comment]
Just need to use a newer version of node.  Updating to a modern version, such as 5.0.0, will fix this problem.

**Comment by mcdonnelldean** [comment]
I think the latest version of 4.x will work too.

**Comment by bmnepali** [comment]
I'm running OSX El Capitan 10.11.5 and also i have installed node v4.4.2, v5.10.0 and v6.0. i have tried to install phonegap globally but keeps be displaying the warning. Above mentioned solutions don't worked out for me.

**Comment by kasongoyo** [comment]
I had the same problem in ubuntu16 64bit and i fixed it by installing ubuntu build-essentials then remove $HOME/node-gyp and reinstalling my native module.

**Comment by mcdonnelldean** [comment]
Merged with #22 It's a dependency issue.

**Comment by amir-rahnama** [comment]
I'm getting the same error with Node v6.3.0

**Comment by pfortuna** [comment]
I'm getting the error with Node v6.4.0

**Comment by hugufc** [comment]
I'm getting the error with Node v6.6.0 running on Mac

**Comment by lfreneda** [comment]
Getting with 6.4, any ideas?

**Comment by HankLiang** [comment]
I'm getting the error with Node v6.2.0

**Comment by dlrice** [comment]
Also seen with Node v6.9.1

**Comment by ejbp** [comment]
Also seen with Node 7.0.0. Update: After some research I figured out why. Check this link: https://github.com/nodejs/node-gyp/issues/942

Basically this is the reason of my problem:

> It transpires that nvm sets the NVM_NODEJS_ORG_MIRROR variable in the latest version of nvm.sh and, indeed, NODEJS_ORG_MIRROR is not set.
> 
> So, it seems like bcrypt isn't going to install correctly when NVM_NODEJS_ORG_MIRROR is removed, and end-users will have to explicitly configure NODEJS_ORG_MIRROR. It seems like a potentially unnecessary configuration step for a lot of people.

**Comment by mtrabelsi** [comment]
Same here with 7.3.0 !

**Comment by coolegos** [comment]
Same here with 7.4.0 ! I return to 5.0.0  is ok.

**Comment by chakrihacker** [comment]
Same with 6.10.0
