### ISSUE TITLE
Ensure all steps work on Windows

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/micro-services-tutorial-iot#21]
Confirmed Working:

- [x] Step0
- [x] Step1
- [x] Step2
- [x] Step3
- [x] Step4
- [x] Step5
- [x] Step6
- [x] Step7
- [x] Step8

**Comment by mihaidma** [comment]
verified on W7 with cmd and git bash, all steps work.

**Comment by mcdonnelldean** [comment]
verfied on W10 with cmd, all steps working. Data in Influx too.
